---
name: iCal-Parser-SAX
version: 1.07
author:
  - 'Rick Frankel, cpan@rickster.com'
abstract: Generate SAX events from an iCalendar
license: perl
requires:
  DateTime: 0.22
  IO::File: 1.1
  IO::String: 1.05
  XML::SAX::Base: 1.04
  XML::SAX::Writer: 0.44
  iCal::Parser: 1.07
recommends:
  LWP::UserAgent: 2.032
build_requires:
  Test::More: 0.47
  Test::XML: 0.06
provides:
  iCal::Parser::SAX:
    file: lib/iCal/Parser/SAX.pm
    version: 1.07
generated_by: Module::Build version 0.261
