# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         iCal-Parser-SAX
version:      1.02
version_from: lib/iCal/Parser/SAX.pm
installdirs:  site
requires:
    DateTime:                      0.22
    iCal::Parser:                  1.01
    IO::File:                      1.1
    IO::String:                    1.05
    Test::More:                    0.47
    Test::XML:                     0.06
    XML::SAX::Base:                1.04
    XML::SAX::Writer:              0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
